create database customer;
USE customer;
select * from customer_data limit 10;
SHOW COLUMNS FROM customer_data;
DESCRIBE customer_data;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)as total_revenue
from customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer_data
where discount_applied= 'yes' and purchase_amount >= (select avg(purchase_amount) from customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS highest_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY highest_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type ,round(avg(purchase_amount),2)as avg_purchase
from customer_data
where shipping_type in ('standard','express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_cust,round(avg(purchase_amount),2)avg_spend,sum(purchase_amount)as total_rev
from customer_data
group by subscription_status
order by avg_spend,total_rev desc;

-- 06. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE
        WHEN discount_applied = 'Yes' THEN 1
        ELSE 0
    END) AS discount_purchases,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*),
            2) AS discount_percentage
FROM
    customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- 07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases <=1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_segment;
  
-- Q8. What are the top 3 most purchased products within each category?
WITH product_sales AS (
    SELECT category,item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer_data
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    purchase_count
FROM product_sales
WHERE rn <= 3
ORDER BY category, purchase_count DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_contribution_pct
FROM customer_data
GROUP BY age_group
ORDER BY revenue_contribution_pct DESC;
